-- Exemplo 1 – Criação de tabela sem nenhuma constraint criada no grupo de arquivo (filegroup) Primary
CREATE DATABASE DB_TABELAS
ON PRIMARY ( NAME = N'DB_TABELAS',
FILENAME = N'C:\Databases\DB_TABELAS.mdf' ),
FILEGROUP DADOS
( NAME = N'DB_TABELAS_DADOS',
FILENAME = N'C:\Databases\DB_TABELAS_DADOS.ndf' )
LOG ON
( NAME = N'DB_TABELAS_log', FILENAME = N'C:\Databases\DB_TABELAS_
log.ldf' )
GO

USE DB_TABELAS
GO

CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER ,
NOM_ALUNO VARCHAR (60) ,
NUM_CPF NUMERIC (11) ,
NUM_RG NUMERIC (12) ,
DES_EMAIL VARCHAR (80) ,
DAT_NASCIMENTO DATETIME
)

-- Exemplo 2 – Criação de tabela sem nenhuma constraint criada no grupo de arquivo (filegroup) DADOS

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO

CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER ,
NOM_ALUNO VARCHAR (60) ,
NUM_CPF NUMERIC (11) ,
NUM_RG NUMERIC (12) ,
DES_EMAIL VARCHAR (80) ,
DAT_NASCIMENTO DATETIME
) ON DADOS


-- Exemplo 3 – Tabela com constraint de not null:

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO

CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL
)
ON DADOS


-- Exemplo 4 – Criação de tabela com constraint de chave primária nomeada e campos not null:
DROP TABLE IF EXISTS TB_ALUNO


CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL ,
CONSTRAINT ALUNO_PK PRIMARY KEY CLUSTERED (COD_ALUNO)
)
ON DADOS


-- a constraint foi declarada no mesmo local que a coluna:

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO

CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL CONSTRAINT ALUNO_PK PRIMARY KEY
CLUSTERED,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL)
ON DADOS



--Exemplo 5 – Criação de tabela com constraint de chave primária não nomeada e campos not null:
CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL PRIMARY KEY ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL
)
ON DADOS


--Exemplo 6 – Criação de tabela com constraint de chave primária nomeada, campos not null e índice da chave primária em outro grupo de arquivos (filegroup):
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO

CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL ,
CONSTRAINT ALUNO_PK PRIMARY KEY CLUSTERED (COD_ALUNO)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS
GO
CREATE TABLE TB_MATRICULA
(
NUM_MATRICULA INTEGER NOT NULL ,
DAT_MATRICULA DATETIME NOT NULL ,
VAL_MATRICULA DECIMAL (12,2) NOT NULL ,
ALUNO_COD_ALUNO INTEGER NOT NULL ,
CONSTRAINT MATRICULA_PK PRIMARY KEY CLUSTERED (NUM_MATRICULA)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS
GO


--Exemplo 7 – Criação de chave única (primeira forma):
CREATE UNIQUE NONCLUSTERED INDEX
UK_ALUNO_CPF ON TB_ALUNO
(
NUM_CPF
)
ON INDICES
GO
CREATE UNIQUE NONCLUSTERED INDEX
UK_ALUNO_RG ON TB_ALUNO
(
NUM_RG
)
ON INDICES
GO
CREATE UNIQUE NONCLUSTERED INDEX
UK_ALUNO_EMAIL ON TB_ALUNO
(
DES_EMAIL
)
ON INDICES
GO


--Exemplo 8 – Criação de chave única (segunda forma):
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO
CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL ,
NUM_RG NUMERIC (12) NOT NULL ,
DES_EMAIL VARCHAR (80) NOT NULL ,
DAT_NASCIMENTO DATETIME NOT NULL ,
CONSTRAINT UK_ALUNO_CPF UNIQUE (NUM_CPF),
CONSTRAINT UK_ALUNO_RG UNIQUE (NUM_RG),
CONSTRAINT UK_ALUNO_EMAIL UNIQUE (DES_EMAIL),
CONSTRAINT ALUNO_PK PRIMARY KEY CLUSTERED (COD_ALUNO)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS



-- Exemplo 9 – Criação de chave única (terceira forma):
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO
CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) NOT NULL ,
NUM_CPF NUMERIC (11) NOT NULL CONSTRAINT UK_ALUNO_CPF UNIQUE ,
NUM_RG NUMERIC (12) NOT NULL CONSTRAINT UK_ALUNO_RG UNIQUE ,
DES_EMAIL VARCHAR (80) NOT NULL CONSTRAINT UK_ALUNO_EMAIL
UNIQUE,
DAT_NASCIMENTO DATETIME NOT NULL ,
CONSTRAINT ALUNO_PK PRIMARY KEY CLUSTERED (COD_ALUNO)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS

--Exemplo 10 – Criação de tabela com constraint de chave primária nomeada, campos not null e índice da chave primária em outro grupo de arquivos
(filegroup) e chave estrangeira:
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_MATRICULA')
DROP TABLE TB_MATRICULA
GO
CREATE TABLE TB_MATRICULA
(
NUM_MATRICULA INTEGER NOT NULL ,
DAT_MATRICULA DATETIME NOT NULL ,
VAL_MATRICULA DECIMAL (12,2) NOT NULL ,
COD_ALUNO INTEGER NOT NULL ,
FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO),
CONSTRAINT MATRICULA_PK PRIMARY KEY CLUSTERED (NUM_MATRICULA)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS
GO


-- Exemplo 11 – Criação de tabela com constraint de chave primária nomeada, campos not null e índice da chave primária em outro grupo de arquivos
-- (filegroup), chave estrangeira e constraint de check:
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_MATRICULA')
DROP TABLE TB_MATRICULA
GO
CREATE TABLE TB_MATRICULA
(
NUM_MATRICULA INTEGER NOT NULL ,
DAT_MATRICULA DATETIME NOT NULL ,
VAL_MATRICULA DECIMAL (12,2) NOT NULL ,
COD_ALUNO INTEGER NOT NULL ,
FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO),
CHECK(VAL_MATRICULA > 0),
CONSTRAINT MATRICULA_PK PRIMARY KEY CLUSTERED (NUM_MATRICULA)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS
GO


--Exemplo 12 – Segunda forma de criar chave estrangeira:
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_MATRICULA')
DROP TABLE TB_MATRICULA
GO
CREATE TABLE TB_MATRICULA
(
NUM_MATRICULA INTEGER NOT NULL ,
DAT_MATRICULA DATETIME NOT NULL ,
VAL_MATRICULA DECIMAL (12,2) NOT NULL ,
COD_ALUNO INTEGER NOT NULL FOREIGN KEY REFERENCES TB_
ALUNO(COD_ALUNO),
CHECK(VAL_MATRICULA > 0),
CONSTRAINT MATRICULA_PK PRIMARY KEY CLUSTERED (NUM_MATRICULA)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON INDICES
)
ON DADOS
GO

/*******************************************************************************************************************************************/

--Exemplo 1 – Adicionando uma nova coluna em uma tabela:
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME ='TB_ALUNO')
DROP TABLE TB_ALUNO
GO
CREATE TABLE TB_ALUNO
(
COD_ALUNO INTEGER NOT NULL ,
NOM_ALUNO VARCHAR (60) ,
NUM_CPF NUMERIC (11) ,
NUM_RG NUMERIC (12) ,
DES_EMAIL VARCHAR (80) ,
DAT_NASCIMENTO DATETIME
)
GO
ALTER TABLE TB_ALUNO ADD DAT_CADASTRO DATETIME;


-- Exemplo 2 – Adicionando mais de uma nova coluna em uma tabela:
ALTER TABLE TB_ALUNO ADD DATA_CADASTRO DATETIME,SIT_ATIVO CHAR(1) NOT NULL


-- Exemplo 3 – Adicionando uma constraint (chave primária, única e estrangeira) em uma tabela:
ALTER TABLE TB_ALUNO ADD CONSTRAINT ALUNO_PK PRIMARY KEY (COD_ALUNO)
ALTER TABLE TB_ALUNO ADD CONSTRAINT UK_ALUNO_EMAIL UNIQUE (DES_EMAIL)

ALTER TABLE TB_MATRICULA ADD CONSTRAINT FK_ALUNO_MATRICULA
FOREIGN KEY(COD_ALUNO) REFERENCES TB_ALUNO (COD_ALUNO)

--Ou:
ALTER TABLE TB_ALUNO ADD PRIMARY KEY (COD_ALUNO)
ALTER TABLE TB_ALUNO ADD UNIQUE (DES_EMAIL)
ALTER TABLE TB_MATRICULA ADD FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO (COD_ALUNO)



-- Exemplo 4 – Eliminando uma chave primária, única ou estrangeira:
ALTER TABLE TB_ALUNO DROP CONSTRAINT ALUNO_PK
ALTER TABLE TB_ALUNO DROP CONSTRAINT UK_ALUNO_EMAIL
ALTER TABLE TB_MATRICULA DROP CONSTRAINT FK_ALUNO_MATRICULA

--Exemplo 5 – Para desabilitar qualquer constraint específica:
--Criação da CONSTRAINT
ALTER TABLE TB_MATRICULA ADD CONSTRAINT CK_MATRICULA_DT_NAO_PODE_SER_FUTURA CHECK (DAT_MATRICULA>=GETDATE() )

--Desabilita a CONSTRAINT
ALTER TABLE TB_MATRICULA NOCHECK CONSTRAINT CK_MATRICULA_DT_NAO_PODE_SER_FUTURA

--Exemplo 6 – Para desabilitar todas as constraints de uma tabela:
ALTER TABLE TB_MATRICULA NOCHECK CONSTRAINT ALL

-- Exemplo 7 – Para habilitar uma constraint específica:
ALTER TABLE TB_MATRICULA CHECK CONSTRAINT FK_ALUNO_MATRICULA

-- Exemplo 8 – Para habilitar todas as constraints em uma tabela:
ALTER TABLE TB_MATRICULA CHECK CONSTRAINT ALL

-- Exemplo 9 – Para eliminar uma coluna da tabela:
ALTER TABLE TB_ALUNO DROP COLUMN DAT_CADASTRO

-- Exemplo 10 – Para renomear uma tabela (o comando não é ALTER e sim SP_RENAME):

EXEC SP_RENAME 'TB_MATRICULA', 'MATRICULA_ALUNO'

-- Exemplo 11 – Para visualizar a estrutura da tabela:

EXEC SP_HELP 'TB_MATRICULA'

-- Exemplo 12 – Para listar as tabelas de um banco de dados:
SELECT * FROM SYS.TABLES
SELECT * FROM SYSOBJECTS WHERE XTYPE = 'U'
EXEC SP_TABLES

-- Exemplo 13 – Para eliminar uma tabela:
DROP TABLE TB_MATRICULA

