

USE PEDIDOS
GO
--Criação da tabela
CREATE TABLE TB_VENDA (
ID INT IDENTITY PRIMARY KEY,
USUARIO SYSNAME, --CAMPO QUE SERÁ UTILIZADO PARA A
FILTRAGEM
NUM_PEDIDO INT,
COD_PRODUTO VARCHAR(10),
VALOR DECIMAL(10,2),
QUANTIDADE INT
)
GO
INSERT INTO TB_VENDA VALUES
( 'USERSP', 1, 'ABC452', 150.00,2),
( 'USERMG', 2, 'A584452', 758.00,1),
( 'USERRJ', 3, 'BC8452', 10.00,1),
( 'USERSP', 4, 'DUO985', 1650.00,2),
( 'USERRJ', 5, '98751', 1050.00,4),
( 'USERRJ', 6, 'PPP980', 870.00,7),
( 'USERSP', 7, 'CCI989', 753.00,8),
( 'USERSP', 8, 'LIU90', 258.00,9),
( 'USERSP', 9, 'NHY98', 951.00,10),
( 'USERMG', 10, 'SOIU0', 25.00,11)


--CRIAÇÃO DOS USUÁRIOS
CREATE USER USERSP WITHOUT LOGIN;
CREATE USER USERRJ WITHOUT LOGIN;
CREATE USER USERMG WITHOUT LOGIN;
CREATE USER GESTOR WITHOUT LOGIN;


-- GRANT DE PERMISSÃO DE SELECT
GRANT SELECT ON TB_VENDA TO USERSP
GRANT SELECT ON TB_VENDA TO USERRJ
GRANT SELECT ON TB_VENDA TO USERMG
GRANT SELECT ON TB_VENDA TO GESTOR
--CRIAÇÃO DE UM SCHEMA QUE SERÁ UTILIZADO PARA O FILTRO
GO
CREATE SCHEMA SCHEMA_VENDA;
GO
CREATE FUNCTION SCHEMA_VENDA.FN_SECURITYPREDICATE(@USUARIO AS
SYSNAME)
RETURNS TABLE
WITH SCHEMABINDING AS
RETURN SELECT 1 AS FN_SECURITYPREDICATE_RESULT
WHERE @USUARIO = USER_NAME() OR USER_NAME() = 'GESTOR';
GO


-- CRIAÇÃO DE UMA POLÍTICA DE SEGURANÇA
GO
--DROP SECURITY POLICY SCHEMA_VENDA.FILTRO_TB_VENDA
CREATE SECURITY POLICY SCHEMA_VENDA.FILTRO_TB_VENDA
ADD FILTER PREDICATE SCHEMA_VENDA.FN_SECURITYPREDICATE(USUARIO)
ON DBO.TB_VENDA
WITH (STATE = ON);
GO
-- TESTANDO COM USUÁRIO DE SP
EXECUTE AS USER = 'USERSP';
SELECT * FROM TB_VENDA
REVERT
GO

-- TESTANDO COM USUÁRIO DO RJ
EXECUTE AS USER = 'USERRJ';
SELECT * FROM TB_VENDA
REVERT
GO

-- TESTANDO COM USUÁRIO DE MG
EXECUTE AS USER = 'USERMG';
SELECT * FROM TB_VENDA
REVERT
GO


-- TESTANDO COM USUÁRIO GESTOR
EXECUTE AS USER = 'GESTOR';
SELECT * FROM TB_VENDA
REVERT
GO














